CREATE TABLE IF NOT EXISTS t_reconciliation_task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL DEFAULT 'demo_user',
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  batch_id VARCHAR(64) DEFAULT NULL,
  task_name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'UPLOADED',
  total_bank_rows INT NOT NULL DEFAULT 0,
  total_clear_rows INT NOT NULL DEFAULT 0,
  auto_fixed_rows INT NOT NULL DEFAULT 0,
  pending_ai_rows INT NOT NULL DEFAULT 0,
  pending_human_rows INT NOT NULL DEFAULT 0,
  unresolved_rows INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_task_user_task (user_id, task_id),
  INDEX idx_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_bank_transaction (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL DEFAULT 'demo_user',
  flow_id VARCHAR(64),
  bank_serial_no VARCHAR(64),
  accounting_date DATE,
  accounting_time TIME,
  value_date DATE,
  self_account_no_masked VARCHAR(64),
  self_account_name_masked VARCHAR(128),
  self_bank_name VARCHAR(128),
  currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
  transaction_type VARCHAR(32),
  transaction_direction VARCHAR(16),
  amount DECIMAL(18,2) NOT NULL,
  debit_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  credit_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  balance_after DECIMAL(18,2),
  trade_time DATETIME NOT NULL,
  account_no_masked VARCHAR(64),
  customer_name_masked VARCHAR(128),
  counterparty_account_no_masked VARCHAR(64),
  counterparty_name_masked VARCHAR(128),
  counterparty_bank_name VARCHAR(128),
  channel VARCHAR(32),
  summary VARCHAR(255),
  purpose VARCHAR(128),
  posting_status VARCHAR(32),
  branch_no VARCHAR(32),
  teller_id VARCHAR(64),
  transaction_code VARCHAR(32),
  source_system VARCHAR(64),
  remark VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_bank_user_task_flow (user_id, task_id, flow_id),
  INDEX idx_task_flow (task_id, flow_id),
  INDEX idx_task_time (task_id, trade_time),
  INDEX idx_bank_serial (bank_serial_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MVP-1: PRD 6.3 mentions HASH partitioning by task_id; not implemented in this baseline DDL.

CREATE TABLE IF NOT EXISTS t_clear_transaction (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL DEFAULT 'demo_user',
  flow_id VARCHAR(64),
  clearing_serial_no VARCHAR(64),
  merchant_id VARCHAR(64),
  merchant_name VARCHAR(128),
  store_name VARCHAR(128),
  terminal_id VARCHAR(64),
  channel VARCHAR(32),
  transaction_type VARCHAR(32),
  trade_date DATE,
  trade_time DATETIME NOT NULL,
  settlement_date DATE,
  amount DECIMAL(18,2) NOT NULL,
  transaction_amount DECIMAL(18,2) NOT NULL,
  fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(18,2) NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
  status VARCHAR(32),
  summary VARCHAR(255),
  batch_no VARCHAR(64),
  voucher_no VARCHAR(64),
  reference_no VARCHAR(64),
  merchant_order_no VARCHAR(64),
  payer_account_no_masked VARCHAR(64),
  payer_name_masked VARCHAR(128),
  payee_account_no_masked VARCHAR(64),
  payee_name_masked VARCHAR(128),
  order_description VARCHAR(255),
  remark VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_clear_user_task_flow (user_id, task_id, flow_id),
  INDEX idx_task_flow (task_id, flow_id),
  INDEX idx_task_time (task_id, trade_time),
  INDEX idx_clear_serial (clearing_serial_no),
  INDEX idx_clear_merchant_order (merchant_order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MVP-1: PRD 6.4 mentions HASH partitioning by task_id; not implemented in this baseline DDL.

CREATE TABLE IF NOT EXISTS t_reconciliation_queue (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL DEFAULT 'demo_user',
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  flow_id VARCHAR(64) NOT NULL,
  bank_transaction_id BIGINT NULL,
  clear_transaction_id BIGINT NULL,
  error_type VARCHAR(32) NOT NULL,
  exception_branch VARCHAR(32) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_AI',
  risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW',
  retry_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_queue_task_flow (task_id, flow_id),
  INDEX idx_queue_task_status (task_id, status),
  INDEX idx_queue_error_type (error_type),
  INDEX idx_error_branch (error_type, exception_branch)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_error_ledger (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  queue_id BIGINT NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL DEFAULT 'demo_user',
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  flow_id VARCHAR(64) NOT NULL,
  error_type VARCHAR(32) NOT NULL,
  exception_branch VARCHAR(32) DEFAULT NULL,
  bank_amount DECIMAL(18,2) DEFAULT NULL,
  clear_amount DECIMAL(18,2) DEFAULT NULL,
  discrepancy_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  ai_cleaned_json JSON,
  ai_audit_opinion TEXT,
  ai_confidence DECIMAL(5,4) DEFAULT NULL,
  rag_source VARCHAR(512),
  handle_status VARCHAR(32) NOT NULL DEFAULT 'UNTREATED',
  handler_username VARCHAR(64),
  handle_remark VARCHAR(255),
  handled_at DATETIME,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_task_error (task_id, error_type),
  UNIQUE KEY uk_ledger_user_task_flow (user_id, task_id, flow_id),
  INDEX idx_handle_status (handle_status),
  INDEX idx_branch_status (exception_branch, handle_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_human_review (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  queue_id BIGINT NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  ai_suggestion VARCHAR(32) NOT NULL,
  ai_confidence DECIMAL(5,4) DEFAULT NULL,
  ai_reason TEXT,
  ai_fallback_level INT NOT NULL DEFAULT 0,
  action VARCHAR(32) NOT NULL,
  handler_username VARCHAR(64) NOT NULL,
  remark VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_agent_execution_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL DEFAULT 'demo_user',
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  task_id VARCHAR(64) NOT NULL,
  queue_id BIGINT NULL,
  agent_name VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  input_payload JSON NOT NULL,
  output_payload JSON NOT NULL,
  rag_retrieval_id BIGINT NULL,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_task_queue (user_id, task_id, queue_id),
  INDEX idx_agent_event (agent_name, event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_rag_retrieval_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL DEFAULT 'demo_user',
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  queue_id BIGINT,
  query_text TEXT NOT NULL,
  top_k INT NOT NULL,
  best_score DECIMAL(8,4),
  sources JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rag_task_queue (task_id, queue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
