CREATE TABLE IF NOT EXISTS t_reconciliation_task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  task_name VARCHAR(128) NOT NULL,
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  status VARCHAR(32) NOT NULL DEFAULT 'UPLOADED',
  total_source_a_rows INT NOT NULL DEFAULT 0,
  total_source_b_rows INT NOT NULL DEFAULT 0,
  auto_fixed_rows INT NOT NULL DEFAULT 0,
  pending_ai_rows INT NOT NULL DEFAULT 0,
  pending_human_rows INT NOT NULL DEFAULT 0,
  unresolved_rows INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_task (user_id, task_id),
  INDEX idx_user_scenario (user_id, scenario_type),
  INDEX idx_user_status (user_id, status),
  INDEX idx_user_task_created (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_source_a_transaction (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  source_side CHAR(1) NOT NULL DEFAULT 'A',
  source_type VARCHAR(32) NOT NULL DEFAULT 'ENTERPRISE_BOOK',
  flow_id VARCHAR(64),
  bank_serial_no VARCHAR(64),
  voucher_no VARCHAR(64),
  accounting_period VARCHAR(16),
  accounting_date DATE,
  accounting_time TIME,
  value_date DATE,
  self_account_no_masked VARCHAR(64),
  self_account_name_masked VARCHAR(128),
  self_bank_name VARCHAR(128),
  account_no_masked VARCHAR(64),
  customer_name_masked VARCHAR(128),
  counterparty_account_no_masked VARCHAR(64),
  counterparty_name_masked VARCHAR(128),
  counterparty_bank_name VARCHAR(128),
  currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
  transaction_type VARCHAR(32),
  transaction_direction VARCHAR(16),
  amount DECIMAL(18,2) NOT NULL,
  debit_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  credit_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  balance_after DECIMAL(18,2),
  trade_time DATETIME NOT NULL,
  channel VARCHAR(32),
  summary VARCHAR(255),
  purpose VARCHAR(128),
  posting_status VARCHAR(32),
  branch_no VARCHAR(32),
  teller_id VARCHAR(64),
  transaction_code VARCHAR(32),
  source_system VARCHAR(64),
  remark VARCHAR(255),
  match_status VARCHAR(32) DEFAULT NULL,
  matched_source_b_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_task_flow (user_id, task_id, flow_id),
  INDEX idx_user_task_time (user_id, task_id, trade_time),
  INDEX idx_user_serial (user_id, bank_serial_no),
  INDEX idx_match_status (task_id, match_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_source_b_transaction (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  source_side CHAR(1) NOT NULL DEFAULT 'B',
  source_type VARCHAR(32) NOT NULL DEFAULT 'BANK_STATEMENT',
  flow_id VARCHAR(64),
  clearing_serial_no VARCHAR(64),
  bank_serial_no VARCHAR(64),
  trade_date DATE,
  settlement_date DATE,
  currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
  amount DECIMAL(18,2) NOT NULL,
  transaction_amount DECIMAL(18,2) NOT NULL,
  fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(18,2) NOT NULL,
  trade_time DATETIME NOT NULL,
  status VARCHAR(32),
  summary VARCHAR(255),
  balance_after DECIMAL(18,2),
  account_no_masked VARCHAR(64),
  customer_name_masked VARCHAR(128),
  counterparty_account_no_masked VARCHAR(64),
  counterparty_name_masked VARCHAR(128),
  counterparty_bank_name VARCHAR(128),
  channel VARCHAR(32),
  remark VARCHAR(255),
  match_status VARCHAR(32) DEFAULT NULL,
  matched_source_a_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_task_flow (user_id, task_id, flow_id),
  INDEX idx_user_task_time (user_id, task_id, trade_time),
  INDEX idx_user_bank_serial (user_id, bank_serial_no),
  INDEX idx_match_status (task_id, match_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_reconciliation_queue (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  source_a_transaction_id BIGINT NULL,
  source_b_transaction_id BIGINT NULL,
  error_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_AI',
  risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW',
  retry_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_task_status (user_id, task_id, status),
  INDEX idx_user_error_type (user_id, error_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_error_ledger (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  queue_id BIGINT NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  flow_id VARCHAR(64) NOT NULL COMMENT 'MVP-0 提前使用：PRD 6.6 经 queue_id 关联，MVP-0 因 queue_id 占位直存',
  error_type VARCHAR(32) NOT NULL,
  discrepancy_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  ai_cleaned_json JSON,
  ai_audit_opinion TEXT,
  ai_confidence DECIMAL(5,4) DEFAULT NULL COMMENT 'MVP-0 提前使用',
  rag_source VARCHAR(512),
  handle_status VARCHAR(32) NOT NULL DEFAULT 'UNTREATED',
  handler_username VARCHAR(64),
  handle_remark VARCHAR(255),
  handled_at DATETIME,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_task_error (user_id, task_id, error_type),
  INDEX idx_user_task_flow (user_id, task_id, flow_id),
  INDEX idx_user_handle_status (user_id, handle_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_rag_retrieval_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  scenario_type VARCHAR(32) NOT NULL DEFAULT 'BANK_ENTERPRISE',
  queue_id BIGINT,
  query_text TEXT NOT NULL,
  top_k INT NOT NULL,
  best_score DECIMAL(8,4),
  sources JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_task_queue (user_id, task_id, queue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
